config/routes.rb
CivicOm::Application.routes.draw do
  
  devise_for :users
  resources :users, :only => :show

  root :to => "community/home#index"

  match '/support' => 'admin/home#support', :as => :support

  

  namespace :community do
    resources :home, :only => :index
  end

  scope ":authority_id" do
    scope :module => "sites" do
      namespace :admin do

        resources :home, :only => :index
        
        resources :topics do
          member do
            get :show_metadata
            get :show_properties
            get :show_records
          end
        end

        resources :data_sources do
          member do
            get :file_source
            post :upload_file
            get :parse
            put :publish
            get :show_records
            get :show_locations
            get :show_metadata
            get :show_associations
            get :show_ddl
          end
        end
        
        resources :maps
        resources :dashboards do
          collection do
            get :new_group
            get :new_measure
          end
        end

        resources :contacts do
          collection do
            get :new_email
            get :new_telephone
            get :new_address
          end
        end

        resources :settings, :only => :index
        resource :site, :except => :destroy

      end
    
      namespace :public do
        resources :home, :only => :index
        resources :maps, :only => [:index, :show]
        resources :dashboards, :only => [:index, :show]
      end
    end
  end
  

end

app/models/linked_data/topic.rb
class LinkedData::Topic < LinkedData::CouchRestModelSchema
  
  attr_reader :instance_database, :instance_database_name, :instance_design_doc, :instance_design_doc_id
  attr_accessor :docs_read, :docs_written
  
  unique_id :identifier

  belongs_to :authority, :class_name => "LinkedData::Authority"
  belongs_to :vocabulary, :class_name => "LinkedData::Vocabulary"
  belongs_to :creator, :class_name => "VCard::Base"
  belongs_to :publisher, :class_name => "VCard::Base"

  # property :instance_database_name, String
  property :instance_class_name, String, :read_only => true
  
  timestamps!

  validates_presence_of :term
  validates_presence_of :authority
  validates_presence_of :instance_database_name
  
  ## Callbacks
  before_create :generate_identifier
  before_create :create_instance_design_doc
  before_destroy :destroy_instance_database

  design do
    view :by_term
    view :by_label
    view :by_authority_id
  end
  
  def record_count
    return 0 if self.instance_class_name.nil?
    instance_database.view("#{self.instance_class_name}/all", {:include_docs => false})["total_rows"]
  end
  
  def instance_database_name
    return if self.authority.nil? || self.term.nil?
    @instance_database_name ||= (%W[#{COUCHDB_CONFIG["db_prefix"]} #{self.authority.term} staging #{COUCHDB_CONFIG["db_suffix"]}].select {|v| !v.blank?}.join("_"))
    
    [self.authority.term, self.term].join('_')
  end
  
  def instance_database
    return unless instance_database_name.present? && self.identifier.present?
    @instance_database ||= COUCHDB_SERVER.database!(instance_database_name)
  end
  
  def instance_design_doc
    return if instance_design_doc_id.nil?
    @instance_design_doc ||= instance_database.get(instance_design_doc_id) 
  end
  
  def instance_design_doc_id
    return if self.instance_class_name.nil?
    @instance_design_doc_id ||= "_design/#{self.instance_class_name}" 
  end
  
  # Provide a CouchRest::Document for this Topic with set database and model_type_key
  def new_instance_doc(options={})
    return if self.instance_class_name.nil?
    params = options.merge(model_type_key.to_sym => self.instance_class_name)
    doc = CouchRest::Document.new(params)
    
    doc.database = instance_database
    doc
  end
   
  def load_instance_docs(docs=[])
    ts = Time.now.utc.iso8601.to_s
    time_stamp = {:created_at => ts, :updated_at => ts}

    # Reserved properties from source doc to ignore during load
    rp = %W[_id _rev model created_at updated_at published]
    db = instance_database

    docs.each do |doc| 
      pub_doc = new_instance_doc(doc.to_hash.delete_if {|k, v| rp.include? k}.merge(time_stamp)) 
      self.docs_read += 1

      pub_doc.save(true)
      self.docs_written += 1
      db.bulk_save if docs_written%500 == 0              
    end
    db.bulk_save
    docs_written
  end
  
  def add_instance_view(*keys)
    return if instance_class_name.nil?
    opts = keys.pop if keys.last.is_a?(Hash)
    opts ||= {}
    ducktype = opts.delete(:ducktype)
    unless ducktype || opts[:map]
      opts[:guards] ||= []
      # opts[:guards].push "(doc['#{model_type_key}'] == '#{self.instance_class_name}')"
      opts[:guards].push "(doc['model'] == '#{self.instance_class_name}')"
    end
    keys.push opts
    dsn = instance_design_doc
    dsn.view_by(*keys)
    dsn.save
  end
  
  # Use bulk_save to delete all data instances for this topic
  def destroy_instance_docs!
    doc_list = instance_design_doc.view(:all)
    destroy_count = doc_list['total_rows']
    return destroy_count if destroy_count < 1
    
    docs = instance_database.get_bulk(doc_list['rows'].map {|rh| rh['id']})
    docs['rows'].each {|rh| instance_database.delete_doc(rh['doc'], false)}
    instance_database.bulk_delete

    destroy_count
  end
  
  def docs_read
    @docs_read ||= 0
  end
  
  def docs_written
    @docs_written ||= 0
  end
  
  # Delete all data instance docs and design doc
  def destroy_instance_database
    instance_database.delete!
  end
  
  # Create a dynamic CouchRest::Model::Base class for this Topic
  def couchrest_model
    ## TODO - deprecate this method
    return if self.term.nil? || instance_database.nil? || self.vocabulary.nil?
    
    write_attribute(:instance_class_name, self.term.singularize.camelize)

    if Object.const_defined?(self.instance_class_name.intern)
      klass = Object.const_get(self.instance_class_name.intern)
    else
      db = instance_database
      prop_list = self.vocabulary.properties.inject([]) {|plist, p| plist << p}
      type_list = self.vocabulary.types.inject([]) {|tlist, t| tlist << t} 
      
      klass = Object.const_set(self.instance_class_name.intern, 
        Class.new(CouchRest::Model::Base) do
          use_database db
          prop_list.each {|p| property p.term.to_sym}
          property :serial_number
          property :data_source_id
          timestamps!

          # type_list.each |t| do
          #   property t.to_sym do
          #     t.properties.each {|tp| property tp.term.to_sym}
          #   end
          # end
          # 
          design do
            view :by_serial_number
            view :by_data_source_id
          end
          
        end
        )
    end
    klass
  end
  
private

  # Instantiate a CouchDB Design Document for this Topic's data
  def create_instance_design_doc
    write_attribute(:instance_class_name, self.term.singularize.camelize)

    ddoc = CouchRest::Document.new(:_id => self.instance_design_doc_id,
                                 :language => "javascript",
                                 :views => {
                                  :all => {
                                    :map =>
                                      "function(doc) {if (doc['#{model_type_key}'] == '#{self.instance_class_name}'){emit(doc['_id'],1);}}"
                                    }
                                  }
                                  )
    
    instance_database.save_doc(ddoc)
    add_instance_vocabulary_views
  end

  # Add instance CouchDB Design Document views for each key in Vocaulary
  def add_instance_vocabulary_views
    return if self.vocabulary.nil?
    self.vocabulary.key_list.each {|k| add_instance_view(k)}
    instance_design_doc
  end

  def spatial_view
    {:spatial => {
      :full => "function(doc) {if (doc.geometry) {emit(doc.geometry, {id: doc._id, geometry: doc.geometry}); }}",
      :minimum => "function(doc) {if (doc.geometry) {emit(doc.geometry, 1); }}"
      }
    }
  end
  
end

app/models/topic.rb
class Topic < DocumentBase
  
  attr_accessor :key_list
  
  # belongs_to :collection, :class_name => "LinkedData::Collection"
  belongs_to :authority
  belongs_to :creator, :class_name => "VCard::Base"
  belongs_to :publisher, :class_name => "VCard::Base"
  
  property :tags, [String]

  property :base_uri, String
  property :curie_prefix, String
  property :curie_suffix, String
  property :property_delimiter, String, :default => "/"
  property :context # Support RDF quads
  
  property :instance_class_name, String, :read_only => true
  
  
  property :properties, [Property]
  collection_of :types

  # Provide enumerations in the following example format:
    # p = {"clown" => {"c" => "circus", "r" => "rodeo"}, "category" => {"a" => "animal", "v" => "vegetable", "m" => "mineral"}}
  property :enumerations, :default => {}

  ## TODO -- move geometries into Properties
  # property :geometries, [GeoJson::Geometry]
  
  timestamps!

  validates_presence_of :term
  validates_presence_of :authority
  validates_format_of :term, with: /^[a-z0-9_]+$/, message: "must be lowercase alphanumerics only"
  validates_length_of :term, maximum: 32, message: "exceeds maximum of 32 characters"
  validates_uniqueness_of :term, :view => 'by_term', message: "is already in use"
  validates_uniqueness_of :identifier, :view => 'all', message: "is already in use"

  ## Callbacks
  before_create :generate_identifier

  design do
    view :by_term
    view :by_label
    view :by_authority_id
    
    view :by_curie_prefix
  
    view :tag_list,
      :map =>
        "function(doc) {
          if (doc['model'] == 'Topic' && doc.tags) {
            doc.tags.forEach(function(tag) {
              emit(tag, 1); 
              });
            }
          }"
          
  end
  
  # view_by :has_geometry,
  #   :map => 
  #     "function(doc) {
  #       if ((doc['model'] == 'Topic') && (doc.geometries.length > 0 )) { 
  #         doc.geometries.forEach(function(geometry) {
  #           emit(geometry, 1);
  #           });
  #         }
  #       }"
  
  def record_count
    return 0 if self.instance_class_name.nil?
    instance_database.view("#{self.instance_class_name}/all", {:include_docs => false})["total_rows"]
  end
  
  def key_list
    return [] if self.properties.nil?
    @key_list ||= self.properties.inject([]) {|list, k| k.key ? list.push(k.term) : list }
  end
  
  def curie
    Hash[self.curie_prefix, self.curie_suffix] if self.curie_prefix && self.curie_suffix
  end
  
  def decode(property_name, key)
    self.enumerations[property_name][key]
  end
  
  def instance_database_name
    return if self.authority.nil? || self.term.nil?
    @instance_database_name ||= (%W[#{COUCHDB_CONFIG["db_prefix"]} #{self.authority.term} staging #{COUCHDB_CONFIG["db_suffix"]}].select {|v| !v.blank?}.join("_"))
    
    [self.authority.term, self.term].join('_')
  end
  
  def instance_database
    return unless instance_database_name.present? && self.identifier.present?
    @instance_database ||= COUCHDB_SERVER.database!(instance_database_name)
  end
  
  def instance_design_doc
    return if instance_design_doc_id.nil?
    @instance_design_doc ||= instance_database.get(instance_design_doc_id) 
  end
  
  def instance_design_doc_id
    return if self.instance_class_name.nil?
    @instance_design_doc_id ||= "_design/#{self.instance_class_name}" 
  end
  
  # Provide a CouchRest::Document for this Topic with set database and model_type_key
  def new_instance_doc(options={})
    return if self.instance_class_name.nil?
    params = options.merge(model_type_key.to_sym => self.instance_class_name)
    doc = CouchRest::Document.new(params)
    
    doc.database = instance_database
    doc
  end
   
  def load_instance_docs(docs=[])
    ts = Time.now.utc.iso8601.to_s
    time_stamp = {:created_at => ts, :updated_at => ts}

    # Reserved properties from source doc to ignore during load
    rp = %W[_id _rev model created_at updated_at published]
    db = instance_database

    docs.each do |doc| 
      pub_doc = new_instance_doc(doc.to_hash.delete_if {|k, v| rp.include? k}.merge(time_stamp)) 
      self.docs_read += 1

      pub_doc.save(true)
      self.docs_written += 1
      db.bulk_save if docs_written%500 == 0              
    end
    db.bulk_save
    docs_written
  end
  
  def add_instance_view(*keys)
    return if instance_class_name.nil?
    opts = keys.pop if keys.last.is_a?(Hash)
    opts ||= {}
    ducktype = opts.delete(:ducktype)
    unless ducktype || opts[:map]
      opts[:guards] ||= []
      # opts[:guards].push "(doc['#{model_type_key}'] == '#{self.instance_class_name}')"
      opts[:guards].push "(doc['model'] == '#{self.instance_class_name}')"
    end
    keys.push opts
    dsn = instance_design_doc
    dsn.view_by(*keys)
    dsn.save
  end
  
  # Use bulk_save to delete all data instances for this topic
  def destroy_instance_docs!
    doc_list = instance_design_doc.view(:all)
    destroy_count = doc_list['total_rows']
    return destroy_count if destroy_count < 1
    
    docs = instance_database.get_bulk(doc_list['rows'].map {|rh| rh['id']})
    docs['rows'].each {|rh| instance_database.delete_doc(rh['doc'], false)}
    instance_database.bulk_delete

    destroy_count
  end
  
  def docs_read
    @docs_read ||= 0
  end
  
  def docs_written
    @docs_written ||= 0
  end
  
  # Delete all data instance docs and design doc
  def destroy_instance_database
    instance_database.delete!
  end

private

  # Instantiate a CouchDB Design Document for this Topic's data
  def create_instance_design_doc
    write_attribute(:instance_class_name, self.term.singularize.camelize)

    ddoc = CouchRest::Document.new(:_id => self.instance_design_doc_id,
                                 :language => "javascript",
                                 :views => {
                                  :all => {
                                    :map =>
                                      "function(doc) {if (doc['#{model_type_key}'] == '#{self.instance_class_name}'){emit(doc['_id'],1);}}"
                                    }
                                  }
                                  )

    instance_database.save_doc(ddoc)
    add_instance_vocabulary_views
  end

  # Add instance CouchDB Design Document views for each key in Vocaulary
  def add_instance_vocabulary_views
    return if self.vocabulary.nil?
    self.vocabulary.key_list.each {|k| add_instance_view(k)}
    instance_design_doc
  end

  def spatial_view
    {:spatial => {
      :full => "function(doc) {if (doc.geometry) {emit(doc.geometry, {id: doc._id, geometry: doc.geometry}); }}",
      :minimum => "function(doc) {if (doc.geometry) {emit(doc.geometry, 1); }}"
      }
    }
  end

end

app/controllers/sites/admin/topics_controller.rb
class Sites::Admin::TopicsController < Sites::AuthenticatedController
  layout 'sites_topics_admin'


  def index
    @topics = Topic.by_authority_id(:key => authority.id)
    render :layout => 'sites_admin'
  end

  def show
    @topic = Topic.get(params[:id])
  end

  def new
    @topic = Topic.new
    # @topic.authority = authority
    @contacts = Vocabularies::VCard::Base.by_authority_id_and_formatted_name.docs
    render :layout => 'sites_admin'
  end

  def create
    @topic = Topic.new(params[:topic])
    @topic.authority = authority
    
    # raise @topic.to_yaml

    if @topic.save
      flash[:success] = 'Successfully created Topic.'
      redirect_to(admin_topic_path(authority, @topic))
    else
      flash[:error] = "Unable to create Topic."
      render :new, :layout => 'sites_admin'
    end
  end
  
  def edit
    @topic = Topic.get(params[:id])
  end

  def update
    @topic = Topic.get(params[:id])
    @topic.attributes = params[:topic]

    respond_to do |format|
      if @topic.save
        flash[:success] = 'Successfully updated Topic.'
        format.html { redirect_to admin_topic_path(authority, @topic) }
        format.xml  { head :ok }
      else
        flash[:error] = "Error updating Topic."
        format.html { render :edit }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end
  

  def show_properties
    @topic = Topic.get(params[:id])
  end

  def edit_properties
    @topic = Topic.get(params[:id])
  end
  
  def update_properties
  end

  def destroy
    @topic = Topic.get(params[:id])
    unless @topic.nil?
      @topic.destroy
      redirect_to(admin_topics_url)
    else
      flash[:error] = "The Topic could not be found, refresh the Topic list and try again."
      redirect_to(admin_topics_url)
    end
  end

end

app/views/sites/admin/topics/_form.html.erb
<% if @topic.errors.any? %>
<div class="row">
	<div class="twelve columns">
			<div class="row">
				<div class="form_errors">
					<h3><%= pluralize(@topic.errors.count, "error") %> prohibited this Topic from being saved:</h3>
					<ul>
						<% @topic.errors.full_messages.each do |msg| %>
							<li><%= msg %><li>
						<% end %>
					</ul>
				</div>
			</div>
			</div>
		</div>
<% end %>
<%= f.hidden_field :rev, :value => @topic['_rev'] if @topic['_rev'] %>
<%#= debug @topic.to_yaml %>
		
<div class="row">
	<div class="four columns">
		<%= f.label :label %> <%= f.text_field :label, :class=>'input-text medium' %>
	</div>
	<div class="four columns">
		<%= f.label :term %> <%= f.text_field :term, :class=>'input-text medium' %>
	</div>
</div>

<div class="row">
	<%= f.label :comment %> <%= f.text_area :comment, :rows => 3, :class=>'text-area large' %>
</div>
<div class="row">
	<%= f.label :creator_id, "Creator" %> 
	<%#= f.collection_select :creator_id, @contacts, :authority_id, :formatted_name, {:prompt => 'Select Contact'} %>
</div>

<div class="row">
	<%= f.submit "Save", :class => "nice medium radius blue button" %> 
	<%= link_to 'Back', :back, :class => "small white nice button radius" %> 
</div>		

app/views/sites/admin/topics/edit.html.erb
<% title "Topics" %>
<div class="row">
	<div class="five columns">
		<h3><%= "Edit #{@topic.label}" %></h3>
	</div>
	<div class="three column">
    <%= link_to "Delete", admin_topic_path(authority, @topic), :confirm => 'Are you sure?', :method => :delete, :class => "nice medium radius blue button" %>
	</div>
	<div class="three columns">
	  <%= link_to "List All", admin_topics_path(authority), :class => "nice medium radius orange button" %>
	</div>
</div>
<div class="row">
	<div id="forms">
	  <%= form_for :topic, :url => admin_topic_path(authority, @topic), :html => {:method=>:put, :class=>"nice"} do |f| %>
		  <%= render :partial => 'form', :locals => {:f => f} %>
	  <% end %>
	</div>
</div>

app/views/sites/admin/topics/index.html.erb
<% title "Topics" %>
<div class="row">
	<div class="three columns">
		<h3>All Topics</h3>
	</div>
	<div class="three columns">
	  <%= link_to 'Add Topic', new_admin_topic_path, :class => "nice medium radius blue button" %> </p>
	</div>
</div>
<div class="row">
	<div class="twelve columns">
		<ul>
			<% if @topics.count < 1 %>
				<li>No Topics found</li>
			<% end %>
			<% @topics.each do |topic| %>
			  <li><%= link_to topic.label, admin_topic_path(authority, topic) %></li>
			<% end %>
		</ul>
	</div>
</div>

app/views/sites/admin/topics/new.html.erb
<% title "Topics" %>
<div class="row">
	<div class="three columns">
		<h3>Add Topic</h3>
	</div>
	<div class="three columns">
	  <%= link_to "List Topics", admin_topics_path(authority), :class => "nice medium radius blue button" %>
	</div>
</div>
<div id="forms">
  <%= form_for :topic, :url => admin_topics_path, :html => {:class => "nice"} do |f| %>
  	<%= render :partial => 'form', :locals=> {:f => f} %>
  <% end %>
</div>

app/views/sites/admin/topics/show.html.erb
<% title "Topics" %>
<div class="row">
	<div class="five columns">
		<h3><%= @topic.label %></h3>
	</div>
	<div class="one column">
    <%= link_to "Edit", edit_admin_topic_path(authority, @topic), :class => "nice medium radius blue button" %>
	</div>
	<div class="three columns">
    <%= link_to "List Topics", admin_topics_path(authority), :class => "nice medium radius blue button" %>
	</div>
</div>
<div class="row">
	<div class="five columns">
		<ul>
			<hr/>
			<li>Records: <strong><%= @topic.record_count %></strong></li>
			<hr/>
			<li>Last update: <strong><%= "Jan 1, 2012" %></strong></li>
			<hr/>
			<li>Comment: <strong><%= @topic.comment %></strong></li>
		</ul>
	</div>
</div>
<div class="row">
	<% @topic.properties.each do |prop| %>
	<% end %>
</div>

app/views/sites/admin/topics/show_properties.html.erb
<% title "Topics" %>
<div class="row">
	<div class="four columns">
		<h3><%= @topic.label %></h3>
	</div>
	<div class="three columns">
	  <%= link_to "List Topics", admin_topics_path(authority), :class => "nice medium radius orange button" %>
	</div>
</div>
<div class="row">
	<div id="forms">
	</div>
</div>