config/routes.rb
CivicOm::Application.routes.draw do
  
  devise_for :users
  resources :users, :only => :show

  root :to => "community/home#index"

  match '/support' => 'admin/home#support', :as => :support

  

  namespace :community do
    resources :home, :only => :index
  end

  scope ":authority_id" do
    scope :module => "sites" do
      namespace :admin do

        resources :home, :only => :index
        
        resources :topics do
          member do
            get :show_metadata
            get :show_properties
            get :show_records
          end
        end

        resources :data_sources do
          member do
            get :file_source
            post :upload_file
            get :parse
            put :publish
            get :show_records
            get :show_locations
            get :show_metadata
            get :show_associations
            get :show_ddl
          end
        end
        
        resources :maps
        resources :dashboards do
          collection do
            get :new_group
            get :new_measure
          end
        end

        resources :contacts do
          collection do
            get :new_email
            get :new_telephone
            get :new_address
          end
        end

        resources :settings, :only => :index
        resource :site, :except => :destroy

      end
    
      namespace :public do
        resources :home, :only => :index
        resources :maps, :only => [:index, :show]
        resources :dashboards, :only => [:index, :show]
      end
    end
  end
  

end

app/models/dashboard/base.rb
module Dashboard
  class Base < CouchRest::Model::Base
    use_database SCHEMA_DATABASE
    
    belongs_to :authority

    FORMATS = %w(percentage currency number string)
    VISUALS = %w(inlinesparkline pie inlinebar bullet)

    property :title
    property :description
    property :groups, [Dashboard::Group], :default => []

    timestamps!

    validates_presence_of :title
    validates_presence_of :authority
    
    design do
      view :by_authority_id
    end
    
  end
end

app/models/dashboard/group.rb
module Dashboard
  class Group < Hash
    include CouchRest::Model::Embeddable

    property :title
    property :description
    property :measures, [Dashboard::Measure], :default => []

  end
end

app/models/dashboard/measure.rb
module Dashboard
  class Measure < Hash
    include CouchRest::Model::Embeddable

    property :measure
    property :source_class 
    property :source_property
    property :sort_property  
    property :measure_source_organization
    property :measure_source_url
    property :format
    property :visual
    property :rank
    property :values, :default=>[]

    def values
      if self['values'].empty? && !self.source_class.blank? && !self.source_property.blank?
        if !self.sort_property.blank?
          self['values'] = OpenMedia::Schema.get_records(self.source_class).sort{|r1,r2| r1[self.sort_property] <=> r2[self.sort_property]}.collect{|r| r[self.source_property]}
        else
          self['values'] = OpenMedia::Schema.get_records(self.source_class).collect{|r| r[self.source_property]}
        end
        # HACKETY HACK
        self['values'] = self['values'].select{|v| v != "0.0" && v!="0" && v!=''}

      end
      self['values']
    end

  end
end

app/controllers/sites/admin/dashboards_controller.rb
class Sites::Admin::DashboardsController < Sites::AuthenticatedController

  def index
    @dashboards = Dashboard::Base.by_authority_id(:key => authority.id)
  end

  def show
    @dashboard = Dashboard::Base.get(params[:id])
  end

  def new
    @dashboard = Dashboard::Base.new
    @dashboard_group = Dashboard::Group.new
  end

  def new_group
    render :partial=>'form_dashboard_group', :locals=> { :group=>Dashboard::Group.new }
  end

  def new_measure
    render :partial=>'form_measure', :locals=> { :measure=>Dashboard::Measure.new }
  end


  def create
    @dashboard = Dashboard::Base.new(params[:dashboard])
    @dashboard.authority = authority

    if @dashboard.save
      flash[:success] = 'Successfully created Dashboard.'
      redirect_to(admin_dashboard_path(authority, @dashboard))
    else
      flash[:error] = 'Unable to create Dashboard.'
      render :action => "new"
    end
  end

  def edit
    @dashboard = Dashboard::Base.get(params[:id])
    @dashboard_groups = @dashboard.groups
  end

  def update
    @dashboard = Dashboard::Base.get(params[:id])
    @dashboard.attributes = params[:dashboard]
    @dashboard.groups = nil unless params[:dashboard][:groups]
    respond_to do |format|
      if @dashboard.save
        flash[:success] = 'Successfully updated Dashboard.'
        format.html { redirect_to(admin_dashboard_path(authority, @dashboard)) }
        format.xml  { head :ok }
      else
        flash[:error] = "Error updating Dashboard."
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dashboard.errors, :status => :unprocessable_entity }
      end
    end
  end


  # DELETE /dashboards/:id
  def destroy
    @dashboard = Dashboard::Base.get(params[:id])
    unless @dashboard.nil?
      @dashboard.destroy
      redirect_to(admin_dashboards_url)
    else
      flash[:error] = "The Dashboard could not be found, refresh the Dashboard list and try again."
      redirect_to(admin_dashboards_url)
    end
  end

end

app/views/sites/admin/dashboards/_form.html.erb
<div class="row">
	<div class="twelve columns">
		<%#= f.error_messages %>
		<%= f.hidden_field :rev, :value => @dashboard['_rev'] if @dashboard['_rev'] %>
		<div class="row">
			<div class="four columns">
  			<%= f.label :title %> <%= f.text_field :title, :class=>'input-text medium' %>
			</div>
			<div class="four columns">
  			<%= f.label :description, :style => "clear:left;"  %> <%= f.text_area :description, :rows => 2, :class => "text-area large" %>
			</div>
		</div>
		
		<fieldset>
			<legend>Measure Groups</legend>
				<% for group in @dashboard.groups {|p1,p2| p1.title <=> p2.title} %>
						<%= render :partial => 'form_dashboard_group', :locals => {:group => group} %>
					</div>
				<% end %>
				<a href="#" data-url="<%= new_group_admin_dashboards_path(authority, @dashboard) %>" class="add-measure-group add-element">Add Measure Group</a>
		</fieldset>
      
		<div class="row">
			<%= f.submit "Save", :class => "nice medium radius blue button" %> 
			<%= link_to 'Back', :back, :class => "small white nice button radius" %> 
		</div>
  </div>
</div>

app/views/sites/admin/dashboards/_form_dashboard_group.html.erb
<div class="row dashboard-measure-group">
	<div class="row">
		<div class="four columns">
	    <label>Group title</label>
	    <input name="dashboard[groups][][title]" type="text" class='input-text medium'><%= group.title %></input>
		</div>
		<div class="four columns">
	    <label>Description</label>
	    <textarea name="dashboard[groups][][description]" rows="2" class="text-area large"><%= group.description %></textarea>
		</div>
	</div>

  <fieldset>
    <legend>Measures</legend>
    <% for measure in group.measures %>
    	<%= render :partial=>'form_measure', :locals=>{:measure=>measure} %>
    <% end %>
    <a href="#" class="add-measure add-element">Add Measure</a>
  </fieldset>

	<div class="row">
		<a href="#" class="delete-dashboard-group delete-element">Delete Group</a>
	</div>
</div>

app/views/sites/admin/dashboards/_form_measure.html.erb
<div class="row dashboard-measure-group">
	<table class="measure">
		<tr>
	  <td>
	    <label>Measure Label</label><br/>
	    <input name="dashboard[groups][][measures][][measure]" class="standard" type="text" value="<%= measure['measure'] %>"/>
	  </td>
	  <td>
	    <label class='wide'>Sort Property</label><br/>
	    <input name="dashboard[groups][][measures][][sort_property]" class="standard dashboard-property" type="text" value="<%= measure.sort_property %>"/>
	  </td>
	<td>&nbsp;</tr>
	</tr>
		<tr>
	  <td>
	    <label class='wide'>Source Class</label><br/>
	    <input class="standard dashboard-source-class" type="text" value="<%= last_url_component(measure['source_class']) %>"/>
	    <input name="dashboard[groups][][measures][][source_class]" type="hidden" value="<%= measure['source_class'] %>"/>
	  </td>
	  <td>
	    <!-- Present a tdst of Properties from the selected Class above - filter to numeric types -->
	    <label class='wide'>Source Property</label><br/>
	    <input name="dashboard[groups][][measures][][source_property]" class="standard dashboard-property" type="text" value="<%= measure.source_property %>"/>
	  </td>
		<td>&nbsp;</tr>

	</tr>
	<tr>
	  <td>
	    <label class='wide'>Format</label>  <br/>  
	    <select name="dashboard[groups][][measures][][format]", class="standard">
	      <%= options_for_select([''].concat(OpenMedia::Dashboard::FORMATS), measure['format']) %>
	    </select>
	  </td>
	  <td>
	    <label class='wide'>Graph Type</label><br/>
	    <select name="dashboard[groups][][measures][][visual]", class="standard">
	      <%= options_for_select([''].concat(OpenMedia::Dashboard::VISUALS), measure['visual']) %>
	    </select>
	  </td>
		<td>&nbsp;</tr>

	</tr>
	<tr>
	  <td>
	    <label class='wide'>Rank</label><br/>
	    <input name="dashboard[groups][][measures][][rank]" class="standard" type="text" value="<%= measure['rank'] %>"/>
	  </td>
	  <td>
	    <label class='wide'>Description</label><br/>
	    <input name="dashboard[groups][][measures][][description]" class="standard" type="text" value="<%= measure['description'] %>"/>

	  </td>
	  <td style="vertical-align: bottom">
	    <a href="#" class="delete-measure delete-element" alt="Delete">Delete Measure</a>
	  </td>
	</tr>
	</table>
</div>

app/views/sites/admin/dashboards/edit.html.erb
<% title "Edit Dashboard: #{@dashboard.title}" %>
<div id="forms">
  <%= form_for :dashboard, :url => admin_dashboard_path(authority, @dashboard), :html => {:method=>:put, :class=>"nice"} do |f| %>
  	<%= render :partial => 'form', :locals=> {:f=>f} %>
  <% end %>
</div>

app/views/sites/admin/dashboards/index.html.erb
<% title "Dashboards" %>
<div class="row">
	<div class="twelve columns">
		<p><%= link_to 'Add Dashboard', new_admin_dashboard_path %></p>
		<hr />
    <table>
			<thead>
			  <tr>
			    <th>Title</th>
			    <th>Description</th>
			  </tr>
			</thead>
			<% @dashboards.each do |dash| %>
			<tr>
			  <td><%= link_to dash.title, admin_dashboard_path(authority, dash) %></td>
			  <td><%= dash.description %></td>
			</tr>
			<% end %>
    </table>
	</div>
</div>

app/views/sites/admin/dashboards/new.html.erb
<% title "Add Dashboard" %>
<div id="forms">
  <%= form_for :dashboard, :url => admin_dashboards_path, :class => "nice" do |f| %>
  	<%= render :partial => 'form', :locals=> {:f=>f} %>
  <% end %>
</div>

app/views/sites/admin/dashboards/show.html.erb
<% title "Dashboard: #{@dashboard.title}" %>
<div class="grid_12">
	<p>
    <%= link_to 'All Dashboards', admin_dashboards_path %> |
    <%= link_to 'Edit', edit_admin_dashboard_path %> |
    <%= link_to 'Delete', new_admin_dashboard_path %>
  </p>
	<hr />
</div>

<div class="grid_8">
	<% @dashboard.groups.each do |g|  %>
		<%#= render :partial => '/public/dashboards/dashboard_group', :locals  =>{ :group => g } %>
	<% end %>
</div>