config/routes.rb
CivicOm::Application.routes.draw do
  
  devise_for :users
  resources :users, :only => :show

  root :to => "community/home#index"

  match '/support' => 'admin/home#support', :as => :support

  

  namespace :community do
    resources :home, :only => :index
  end

  scope ":authority_id" do
    scope :module => "sites" do
      namespace :admin do

        resources :home, :only => :index
        
        resources :topics do
          member do
            get :show_metadata
            get :show_properties
            get :show_records
          end
        end

        resources :data_sources do
          member do
            get :file_source
            post :upload_file
            get :parse
            put :publish
            get :show_records
            get :show_locations
            get :show_metadata
            get :show_associations
            get :show_ddl
          end
        end
        
        resources :maps
        resources :dashboards do
          collection do
            get :new_group
            get :new_measure
          end
        end

        resources :contacts do
          collection do
            get :new_email
            get :new_telephone
            get :new_address
          end
        end

        resources :settings, :only => :index
        resource :site, :except => :destroy

      end
    
      namespace :public do
        resources :home, :only => :index
        resources :maps, :only => [:index, :show]
        resources :dashboards, :only => [:index, :show]
      end
    end
  end
  

end

app/models/data_source.rb
class DataSource < CouchRest::Model::Base
  
  CSV_SOURCE_TYPE = "csv"
  SHAPEFILE_SOURCE_TYPE = "shapefile"
  URL_SOURCE_TYPE = "url"

  proxied_by :authority
  
  property :term, String        # Escaped vocabulary name suitable for inclusion in IRI
  property :label, String       # User assigned name, RDFS#Label
  property :comment, String     # RDFS#Comment
  property :topics, [LinkedData::Topic]

  property :extract_sets do
    property :serial_number, String
    property :docs_written, Integer
    property :extracted_at, Time
  end

  # property :transform_model do
  #   property :exe_order, Float
  #   property :source_property_term, String
  #   property :destination_topic_id, String
  #   property :destination_topic_property_term, String
  #   property :method, String
  #   property :parameters, String
  # end
  
  timestamps!
  
  validates_presence_of :term

  ## Callbacks
  before_create :init_data_source
  
  design do
    view :by_term
    view :by_label
  end

  def last_extract(view_opts={})
    unless self.extract_sets.nil?
      RawRecord.by_serial_number({:key=>self.extract_sets.last.serial_number}.merge(view_opts))
    end
  end

  def raw_records(view_opts={})
    RawRecord.by_data_source_id({:key=>self.id}.merge(view_opts))
  end  

  def unpublished_raw_records(view_opts={})
    RawRecord.by_unpublished({:key=>self.id}.merge(view_opts))
  end  
  
  def raw_doc_count
    RawRecord.by_data_source_id(:key=>self.id, :include_docs=>false)['rows'].size
  end

  def raw_doc_published_count(view_opts={})
    RawRecord.by_data_source_id_and_published(:startkey=>[self.id], :endkey=>[self.id, {}], :include_docs=>false)['rows'].size
  end
  
  def self.serial_number
    ::Digest::MD5.hexdigest(Time.now.to_i.to_s + rand.to_s).to_s
  end
  
  def extract!(records)
    # return if self.attachments.keys.size = 0

    esn = DataSource.serial_number
    ts = Time.now.utc.iso8601.to_s
    extract_prop_set = {:serial_number => esn, :data_source_id => self.id, 
                        :created_at => ts, :updated_at => ts}
    
    records.each do |rec|
      rr = RawRecord.new
      rr.database = self.database
      rr.database.bulk_save_doc(rec.merge(extract_prop_set))
      self.docs_written += 1
      rr.database.bulk_save if docs_written%500 == 0              
    end
    rr.database.bulk_save
    extract_sets << Hash[:serial_number => esn, :docs_written => docs_written, :extracted_at => ts]
    self.save # Persist the updated extract_sets array 
    extract_sets.last
  end
  
  # def extract(control_file)
  #   control = ETL::Control::Control.resolve(control_file)
  #   p_class = ETL::Parser.const_get("#{parser.to_s.camelize}Parser")
  #   parser = p_class.new(control.sources.first)
  #   rows = parser.collect { |row| row }
  # end
  # 
  
  def transform!
    # generate ctl from dataset and source definition
    ctl = "source :in, {:datasource=>'#{self.id}'}, #{instance_properties}\n"
    ctl << "destination :out,{:order=> #{instance_properties}}\n"

    
    # ctl = "source :in, {:datasource=>'#{self.id}'}, ["+
    #   self.source_properties.collect{|p| p.identifier}.collect{|p| ":#{p}"}.join(',') + "]\n"
    # ctl << "destination :out, {:rdfs_class=>'#{self.rdfs_class_uri}'}, {:order=>[" +
    #   self.rdfs_class.properties.collect{|p| p.identifier}.collect{|p| ":#{p}"}.join(',') + "]}\n"

    ETL::Engine.init(:datasource => self)
    ETL::Engine.process_string(self, ctl)
    ETL::Engine.import = nil
    metadata.update!(:modified => DateTime.now)
    ETL::Engine.rows_written
  end

  def docs_read
    @docs_read ||= 0
  end
  
  def docs_written
    @docs_written ||= 0
  end

private
  def init_data_source
    self.label = self.term.humanize unless self.label.present? 
  end
end

app/models/linked_data/data_source.rb
class LinkedData::DataSource < CouchRest::Model::Base
    
  CSV_SOURCE_TYPE = "csv"
  SHAPEFILE_SOURCE_TYPE = "shapefile"
  URL_SOURCE_TYPE = "url"
  
  belongs_to :authority, :class_name => "LinkedData::Authority"

  property :term, String        # Escaped vocabulary name suitable for inclusion in IRI
  property :label, String       # User assigned name, RDFS#Label
  property :comment, String     # RDFS#Comment
  property :properties, [LinkedData::Property]

  property :file do
    property :original_filename
    property :content_type
    property :tempfile
  end
  
  # property :transform_model do
  #   property :exe_order, Float
  #   property :source_property_term, String
  #   property :destination_topic_id, String
  #   property :destination_topic_property_term, String
  #   property :method, String
  #   property :parameters, String
  # end
  
  timestamps!
  
  validates_presence_of :term
  validates_presence_of :authority
  
  before_create :set_database
  
  
  design do
    view :by_term
    view :by_label
    view :by_authority_id
  end
  
private
  def set_database
    self.database = self.authority.staging_database
  end
  

end

app/controllers/sites/admin/data_sources_controller.rb
require_dependency 'csv'

class Sites::Admin::DataSourcesController < Sites::AuthenticatedController
  layout 'sites_admin'
  before_filter :set_context

  def index
    @data_sources = authority.data_sources.by_label.all
  end
  
  def new
    @data_source = authority.data_sources.new
  end

  def show
    @data_source = authority.data_sources.get(params[:id])
    @data_sets = @data_source.attachments
    render :layout => 'sites_data_sources_admin'
  end

  def create
    @data_source = authority.data_sources.new(params[:data_source])

    if @data_source.save
      flash[:success] = 'Successfully created Data Source.'
      redirect_to(admin_data_source_path(@authority, @data_source))
    else
      flash[:error] = "Unable to create Data Source."
      render :new
    end
  end
  
  def edit
    @data_source = authority.data_sources.get(params[:id])
  end

  def update
    @data_source = authority.data_sources.get(params[:id])
    @data_source.attributes = params[:data_source]

    respond_to do |format|
      if @data_source.save
        flash[:success] = 'Successfully updated Data Source.'
        format.html { redirect_to admin_data_source_path(@authority, @data_source) }
        format.xml  { head :ok }
      else
        flash[:error] = "Error updating Data Source."
        format.html { render :edit }
        format.xml  { render :xml => @data_source.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def file_source
    @data_source = authority.data_sources.get(params[:id])
  end
  
  def upload_file
    # raise params.to_yaml
    # render :text => @uploaded_io.to_json
    @data_source = authority.data_sources.get(params[:id])
    
    @temp = File.open(params[:file_source][:file].tempfile)
    @filename = params[:file_source][:file].original_filename
    @safe_filename = sanitize_filename(@filename)

    @data_source.create_attachment(:name => @safe_filename, :file => @temp)

    respond_to do |format|
      if @data_source.save
        logger.debug("Successfully uploaded file: #{@safe_filename} to db: #{@data_source.database} in doc: #{@data_source.id}")
        
        flash[:success] = "Successfully uploaded file: #{@safe_filename}"
        format.html { redirect_to(admin_data_source_path(@authority, @data_source)) }
        format.xml  { head :ok }
      else
        flash[:error] = "Error uploading file: #{@filename}"
        format.html { render :edit }
        format.xml  { render :xml => @data_set.errors, :status => :unprocessable_entity }
      end
    end
  end  
    
  def parse
    @data_source = authority.data_sources.get(params[:id])
    @attach_name = params[:attach_name]
    @data_set = @data_source.attachments[@attach_name]

    @mime_type = @data_set["content_type"]
    @file_io = @data_source.database.fetch_attachment(params[:id], @attach_name)
    
    case @mime_type
      when "text/csv"
        @records = CSV.parse(@file_io)
        # @parser = Parser::CsvParser.new(@file_io, {:header_row => false})
      when "application/zip"
        @parser = Parser::ShapefileParser.new(@shapefile_name)
    end
    @records
  end
  
  def publish
    raise params.to_yaml
    # render :text => params[:records]
    @data_source = authority.data_sources.get(params[:id])
    @records = params[:records]
    
    # respond_to do |format|
    #   # if @data_source.save
    #   if true
    #     flash[:success] = 'Successfully published uploaded data.'
    #     format.html { redirect_to admin_data_source_path(@authority, @data_source) }
    #     format.xml  { head :ok }
    #   else
    #     flash[:error] = "Error publishing uploaded data."
    #     format.html { render :edit }
    #     format.xml  { render :xml => @data_source.errors, :status => :unprocessable_entity }
    #   end
    # end
    
  end
  
  def show_raw_records
    @data_source = authority.data_sources.get(params[:id])

    count = @data_source.raw_record_count
    records = @data_source.raw_records(:limit => params[:iDisplayLength], :skip => params[:iDisplayStart])

    respond_to do |format|
      format.html
      format.json { render json: DataSourcesShowRawRecords.new(view_context) }
    end
  end
  
  def sanitize_filename(file_name)
    file_name.strip.tap do |name|
      # NOTE: File.basename doesn't work right with Windows paths on Unix
      # get only the filename, not the whole path
      name.sub! /\A.*(\\|\/)/, ''
      # Finally, replace all non alphanumeric, underscore
      # or periods with underscore
      name.gsub! /[^\w\.\-]/, '_'
    end
  end

  def destroy
    @data_source = authority.data_sources.get(params[:id])
    unless @data_source.nil?
      @data_source.destroy
      redirect_to(admin_data_sources_url)
    else
      flash[:error] = "The Data Source could not be found, refresh the Data Source list and try again."
      redirect_to(admin_sources_url)
    end
  end
  
private
  def set_context
    @authority = authority
  end

end

app/views/sites/admin/data_sources/_form.html.erb
<div class="row">
	<div class="twelve columns">
	  <%= f.error_messages %>
		<%= f.hidden_field :rev, :value => @data_source['_rev'] if @data_source['_rev'] %>
		<%#= debug @contact.to_yaml %>
		
		<div class="row">
			<div class="four columns">
				<%= f.label :label %> <%= f.text_field :label, :class=>'input-text medium' %>
			</div>
			<div class="four columns">
				<%= f.label :term %> <%= f.text_field :term, :class=>'input-text medium' %>
			</div>
		</div>
		<div class="row">
			<%= f.label :comment %> <%= f.text_area :comment, :rows => 3, :class=>'text-area large' %>
		</div>
		<div class="row">
			<%= f.label :creator_id, "Creator" %> 
			<%#= f.collection_select :creator_id, @contacts, :authority_id, :formatted_name, {:prompt => 'Select Contact'} %>
		</div>

		<div class="row">
			<%= f.submit "Save", :class => "nice medium radius blue button" %> 
			<%= link_to 'Back', :back, :class => "small white nice button radius" %> 
		</div>		
	</div>
</div>

app/views/sites/admin/data_sources/_upload_file.html.erb
<% title "Data Sources" %>
<div class="row">
	<div class="four columns">
		<h3>Upload Data Set</h3>
	</div>
	<div class="three columns">
	  <%= link_to "List Data Sources", admin_data_sources_path(authority), :class => "nice medium radius orange button" %>
	</div>
</div>
<div class="row">
	<div id="forms">
		<%= form_for :data_packet, :url => upload_admin_data_sources_path(authority.id), :html => {:multipart=>true, :class=>"nice"} do |f| -%>
			<div class="row">
				<h5>Upload File</h5>
			  <%= f.file_field :file, :class => "input-text large" %>
			</div>
			<div class="row">
				<%= f.submit "Upload", :class => "nice medium radius blue button", :disable_with => "Uploading..." %>
				<%= link_to 'Back', :back, :class => "small white nice button radius" %> 
			</div>
		<% end -%>
	</div>
</div>

app/views/sites/admin/data_sources/associations.html.erb
<h1>Sites::Admin::Curate#associations</h1>
<p>Find me in app/views/sites/admin/curate/associations.html.erb</p>

app/views/sites/admin/data_sources/datas_set.html.erb
<h1>Sites::Admin::DataSource#data_set</h1>
<p>Find me in app/views/sites/admin/data_sources/data_set.html.erb</p>

app/views/sites/admin/data_sources/ddl.html.erb
<h1>Sites::Admin::Curate#ddl</h1>
<p>Find me in app/views/sites/admin/curate/ddl.html.erb</p>

app/views/sites/admin/data_sources/edit.html.erb
<% title "Data Sources" %>
<div class="row">
	<div class="five columns">
		<h3><%= "Edit #{@data_source.label}" %></h3>
	</div>
	<div class="three column">
    <%= link_to "Delete", admin_data_source_path(authority, @data_source), :confirm => 'Are you sure?', :method => :delete, :class => "nice medium radius blue button" %>
	</div>
	<div class="four columns">
	  <%= link_to "List Data Sources", admin_data_sources_path(authority), :class => "nice medium radius orange button" %>
	</div>
</div>
<div class="row">
	<div id="forms">
	  <%= form_for :data_source, :url => admin_data_source_path(authority, @data_source), :html => {:method=>:put, :class=>"nice"} do |f| %>
		  <%= render :partial => 'form', :locals => {:f => f} %>
	  <% end %>
	</div>
</div>

app/views/sites/admin/data_sources/file_source.html.erb
<% title "Data Sources" %>
<div class="row">
	<div class="four columns">
		<h3>Upload Data Set</h3>
	</div>
	<div class="four columns">
	  <%= link_to "List Data Sources", admin_data_sources_path(authority, @data_source), :class => "nice medium radius orange button" %>
	</div>
</div>
<div class="row">
	<div id="forms">
		<%= form_for :file_source, :url => upload_file_admin_data_source_path, :html => {:multipart=>true, :class=>"nice"} do |f| -%>
			<div class="row">
				<h5>Upload File</h5>
			  <%= f.file_field :file, :class => "input-text large" %>
			</div>
			<div class="row">
				<%= f.submit "Upload", :class => "nice medium radius blue button", :disable_with => "Uploading..." %>
				<%= link_to 'Back', :back, :class => "small white nice button radius" %> 
			</div>
		<% end -%>
	</div>
</div>

app/views/sites/admin/data_sources/index.html.erb
<% title "Data Sources" %>
<div class="row">
	<div class="four columns">
		<h3>All Data Sources</h3>
	</div>
	<div class="three columns">
	  <%= link_to 'Add Data Source', new_admin_data_source_path(authority), :class => "nice medium radius blue button" %> </p>
	</div>
</div>
<div class="row">
	<div class="twelve columns">
		<ul>
			<% if @data_sources.count < 1 %>
				<li>No Data Sources found</li>
			<% end %>
			<% @data_sources.each do |ds| %>
			  <li><%= link_to ds.label, admin_data_source_path(authority, ds) %></li>
			<% end %>
		</ul>
	</div>
</div>

app/views/sites/admin/data_sources/locations.html.erb
<h1>Sites::Admin::Curate#locations</h1>
<p>Find me in app/views/sites/admin/curate/locations.html.erb</p>

app/views/sites/admin/data_sources/metadata.html.erb
<h1>Sites::Admin::Curate#metadata</h1>
<p>Find me in app/views/sites/admin/curate/metadata.html.erb</p>

app/views/sites/admin/data_sources/new.html.erb
<% title "Data Sources" %>
<div class="row">
	<div class="four columns">
		<h3>Add Data Source</h3>
	</div>
	<div class="three columns">
	  <%= link_to "List Data Sources", admin_data_sources_path(authority), :class => "nice medium radius blue button" %>
	</div>
</div>
<div id="forms">
  <%= form_for :data_source, :url => admin_data_sources_path do |f| %>
  	<%= render :partial => 'form', :locals=> {:f=>f} %>
  <% end %>
</div>

app/views/sites/admin/data_sources/parse.html.erb
<% title "Uploaded Data" %>
<div class="row">
	<div class="seven columns">
		<h3><%= @attach_name %></h3>
	</div>
	<div class="three columns">
    <%= link_to "List Data Sources", admin_data_sources_path, :class => "nice medium radius blue button" %>
	</div>
</div>

<%= form_for @data_source, :url => publish_admin_data_source_path(authority, @data_source), :html => {:method=>:put, :class=>"nice"} do |f| %>
<div class="row">
	<%= f.submit "Publish", :class => "nice medium radius blue button" %> 
	<%= link_to 'Back', :back, :class => "small white nice button radius" %> 
</div>
<div class="row" style="overflow: auto">
  <div class="twelve columns">
    <table id="raw-data-table" data-url="<%= parse_admin_data_source_path(authority, @data_source) %>" class="display">
      <thead>
				<tr>
				  <% @records.first.each do |col| %>
				  <th><%= col %></th>
				  <% end %>
				</tr>
      </thead>
      <tbody>
				<% @records.each do |rec| %>
				<tr>
					<% rec.each do |field| %>
					<td><%= field %></td>
					<% end %>
				</tr>
				<% end %>
      </tbody>
    </table>
 	</div>
</div>
<% end %>

app/views/sites/admin/data_sources/show.html.erb
<% title "Data Sources" %>
<div class="row">
	<div class="four columns">
		<h3><%= @data_source.label %></h3>
	</div>
	<div class="one column">
    <%= link_to "Edit", edit_admin_data_source_path(authority, @data_source), :class => "nice medium radius blue button" %>
	</div>
	<div class="four columns">
    <%= link_to "List Data Sources", admin_data_sources_path, :class => "nice medium radius blue button" %>
	</div>
</div>
<div class="row">
	<div class="ten columns">
		<ul>
			<li>Last upload: <strong><%= "Jan 1, 2012" %></strong></li>
			<li>Term: <strong><%= @data_source.term %></strong></li>
			<li>Comment: <strong><%= @data_source.comment %></strong></li>
		</ul>
		<dl>
			<dt>Last upload:</dt><dd><%= "Jan 1, 2012" %></dd>
			<dt>Term:</dt><dd><%= @data_source.term %></dd>
			<dt>Comment:</dt><dd><%= @data_source.comment %></dd>
		</dl>
	</div>
</div>
<hr/>
<div class="row">
	<div class="four columns">
		<h3>Uploaded Data</h3>
	</div>
	<div class="one columns">
		<%= link_to "Upload", file_source_admin_data_source_path(authority, @data_source), :class => "nice medium radius blue button" %>
	</div>
</div>
<div class="row">
	<div class="ten columns">
		<ul>
			<% if @data_sets.count < 1 %>
				<li>No Data Sets found for this Data Source</li>
			<% end %>
			<% @data_sets.each do |ds| %>
				<% attach_name = ds[0] %>
				<% attach_size = ds[1]['length'] %>
			  <li><%= link_to attach_name, parse_admin_data_source_path(authority, @data_source, {:attach_name => attach_name}) %>
						<%= " (#{number_to_human_size(attach_size)})" %><li>
				<hr/>
			<% end %>
		</ul>
	</div>
</div>