config/routes.rb
CivicOm::Application.routes.draw do
  
  devise_for :users
  resources :users, :only => :show

  root :to => "community/home#index"

  match '/support' => 'admin/home#support', :as => :support

  

  namespace :community do
    resources :home, :only => :index
  end

  scope ":authority_id" do
    scope :module => "sites" do
      namespace :admin do

        resources :home, :only => :index
        
        resources :topics do
          member do
            get :show_metadata
            get :show_properties
            get :show_records
          end
        end

        resources :data_sources do
          member do
            get :file_source
            post :upload_file
            get :parse
            put :publish
            get :show_records
            get :show_locations
            get :show_metadata
            get :show_associations
            get :show_ddl
          end
        end
        
        resources :maps
        resources :dashboards do
          collection do
            get :new_group
            get :new_measure
          end
        end

        resources :contacts do
          collection do
            get :new_email
            get :new_telephone
            get :new_address
          end
        end

        resources :settings, :only => :index
        resource :site, :except => :destroy

      end
    
      namespace :public do
        resources :home, :only => :index
        resources :maps, :only => [:index, :show]
        resources :dashboards, :only => [:index, :show]
      end
    end
  end
  

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
# helper :layout

module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title, page_title.to_s)
  end
    
  def dashboard_title_from_id(id)
    dash = OpenMedia::Dashboard.get(id)
    dash.title
  end
end

app/views/layouts/_assets.html.haml
%meta{:charset => "utf-8"}
%meta{:name => "viewport", :content =>"width=device-width,initial-scale=1"}
%meta{:name => "description", :content => "Publishing system for government open data"}
%meta{:name => "author", :content => "iPublic.org"}

= stylesheet_link_tag "application", :media => "all"
= stylesheet_link_tag "//fonts.googleapis.com/css?family=Droid+Sans|Droid+Serif", :media => "all"
= javascript_include_tag :defaults
= javascript_include_tag :application
= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"

/[if lt IE 9]
  = javascript_include_tag "//html5shim.googlecode.com/svn/trunk/html5.js"

= csrf_meta_tag

app/views/layouts/_footer_admin.html.erb
<div class="four columns">
   <h6><strong>Created by iPublic.org</strong></h6>
	 <p>Civic OpenMedia is made by <%= link_to "iPublic.org", "http://www.ipublic.org/" %>, founded by experienced open data folks.</p>
</div>
 <div class="five columns">
   <h6><strong>OpenMedia site for your community?</strong></h6>
	Interested in starting an OpenMedia site for your community?
</div>
 <div class="three columns">
   <h6><strong>Need help?</strong></h6>
   Licensed under <%= link_to "GPL", "http://www.gnu.org/licenses/gpl.html" %>
   and
	<%= link_to "MIT", "http://www.opensource.org/licenses/mit-license.php" %>
</div>

app/views/layouts/_footer_public.html.erb
<div class="four columns">
   <h6><strong>Created by iPublic.org</strong></h6>
	 <p>Civic OpenMedia is made by <%= link_to "iPublic.org", "http://www.ipublic.org/" %>, founded by experienced open data folks.</p>
</div>
 <div class="five columns">
   <h6><strong>OpenMedia site for your community?</strong></h6>
	Interested in starting an OpenMedia site for your community?
</div>
 <div class="three columns">
   <h6><strong>Need help?</strong></h6>
   Licensed under <%= link_to "GPL", "http://www.gnu.org/licenses/gpl.html" %>
   and
	<%= link_to "MIT", "http://www.opensource.org/licenses/mit-license.php" %>
</div>

app/views/layouts/_header_admin.html.erb
<div class="row">
	<div class="twelve columns">
		<div class="branding">
			<%- if content_for?(:title) %>
				<h2><%= h(yield(:title)) %></h2>
			<%- else %>
				<h2><%= "#{current_site.label} Admin" %></h2>
				<h3 class="subheader"><%= current_site.tag_line %></h3>
			<% end -%>
		</div>
	</div>
</div>

<%- if content_for?(:header) %>
	<div class="row">
		<div class="twelve columns">
			<% yield(:header) %>
		</div>
	</div>
<% end -%>

<% if flash.count > 0 %>
	<div class="row">
		<div class="twelve columns">
			<% flash.each do |name, msg| %>
				<!-- alert-box classes: success, warning, error or blank -->
				<%= content_tag :div, msg, :class => "alert-box #{name}" %>
			<% end %>
		</div>
	</div>	
<% end %>	

app/views/layouts/_header_public.html.erb
<div class="row">
	<div class="twelve columns">
		<div class="branding">
			<h1>Civic OpenMedia</h1>
			<h4 class="subheader">Government Open Data Community</h4>
		</div>
	</div>
</div>

<div class="row">
	<div class="twelve columns">
		<% yield(:header) if content_for?(:header) %>
	</div>
</div>		

<div class="row">
	<div class="twelve columns">
		<% flash.each do |name, msg| %>
			<!-- alert-box classes: success, warning, error or blank -->
			<%= content_tag :div, msg, :class => "alert-box #{name}" %>
		<% end %>
	</div>
</div>		

app/views/layouts/_header_sites_public.html.erb
<div class="row">
	<div class="twelve columns">
		<div class="branding">
			<% if content_for?(:title) %>
				<h1><%= h(yield(:title)) %></h1>
			<% else %>
				<h1><%= "#{current_site.label} Admin" %></h1>
				<h4 class="subheader"><%= current_site.tag_line %></h4>
			<% end %>
		</div>
	</div>
</div>

<div class="row">
	<div class="twelve columns">
		<% yield(:header) if content_for?(:header) %>
	</div>
</div>		

<div class="row">
	<div class="twelve columns">
		<% flash.each do |name, msg| %>
			<!-- alert-box classes: success, warning, error or blank -->
			<%= content_tag :div, msg, :class => "alert-box #{name}" %>
		<% end %>
	</div>
</div>

app/views/layouts/_nav_data_sources.html.erb
<dl class="nice tabs vertical hide-on-phones">
	<dd><%= link_to "Metadata", show_metadata_admin_data_source_path(authority, @data_source) %></dd>
	<dd><%= link_to "Locations", show_locations_admin_data_source_path(authority, @data_source) %></dd>
	<dd><%= link_to "Associations", show_associations_admin_data_source_path(authority, @data_source) %></dd>
	<dd><%= link_to "DDL", show_ddl_admin_data_source_path(authority, @data_source) %></dd>
	<dd></dd>
</dl>

app/views/layouts/_nav_topics.html.erb
<dl class="nice tabs vertical hide-on-phones">
	<dd><%= link_to "Topic", admin_topic_path(authority, @topic), :class => "active" %></dd>
	<dd><%= link_to "Properties", show_properties_admin_topic_path(authority, @topic) %></dd>
	<dd><%= link_to "Records", show_records_admin_topic_path(authority, @topic) %></dd>
	<dd></dd>
</dl>

app/views/layouts/_om_bar.html.erb
<div class="container" id="omBar">
  <div class="row">
    <div class="four columns">
      <h1><%= link_to "Civic OpenMedia: #{current_site.label}", admin_home_index_path %></h1>
    </div>
    <div class="eight columns hide-on-phones">
			<strong class="right">
					<%= link_to 'Home', admin_home_index_path %>
					<%= link_to 'Topics', admin_topics_path(authority), :title => "" %>
					<%= link_to 'Data Sources', admin_data_sources_path(authority), :title => "" %>
					<%= link_to 'Maps', admin_maps_path(authority), :title => "" %>
					<%= link_to 'Dashboards', admin_dashboards_path(authority), :title => "" %>
					<%= link_to 'Contacts', admin_contacts_path(authority), :title => "" %>
					<%= link_to 'Settings', admin_settings_path(authority), :title => "" %>
					<%= link_to 'Community', community_home_index_path %>
			</strong>
    </div>
  </div>
</div>

app/views/layouts/sites_admin.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <%= render :partial => 'layouts/resources' %>
		<title><%= content_for?(:title) ? "Civic OpenMedia Online: " + h(yield(:title)) : "Civic OpenMedia Online" %></title>
		<%= javascript_include_tag "application" %>
		<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" %>
		<%= javascript_include_tag "jquery.formalize" %>
	</head>
	<body>
		<div id="omBar" class="container">
	    <div class="row">
	      <div class="four columns">
	        <h1><%= link_to "Civic OpenMedia: #{current_site.label}", admin_home_index_path %></h1>
	      </div>
	      <div class="eight columns hide-on-phones">
					<strong class="right">
							<%= link_to 'Home', admin_home_index_path %>
							<%= link_to 'Data Sources', admin_data_sources_path, :title => "" %>
							<%= link_to 'Collections', admin_data_sources_path, :title => "" %>
							<%= link_to 'Maps', admin_maps_path, :title => "" %>
							<%= link_to 'Dashboards', admin_dashboards_path, :title => "" %>
							<%= link_to 'Site', admin_site_path(authority), :title => "" %>
							<%= link_to 'Contacts', admin_contacts_path(authority), :title => "" %>
							<%= link_to 'Community', community_home_index_path %>
					</strong>
	      </div>
	    </div>
	  </div>
	  
		<div class="container header">
			<div class="row">
				<div class="twelve columns">
					<div class="branding">
						<% if content_for?(:header) %>
							<%= yield(:header) %>
						<% else %>
							<h1><%= "#{current_site.label} Admin" %></h1>
							<h4 class="subheader"><%= current_site.tag_line %></h4>
						<% end %>
					</div>
				</div>
			</div>
			
		<div class="container content">
				<div class="row">
					<div class="twelve columns">
						<% flash.each do |name, msg| %>
							<!-- alert-box classes: success, warning, error or blank -->
							<%= content_tag :div, msg, :class => "alert-box #{name}" %>
							<p class="notice"><%= notice %></p>
							<p class="alert"><%= alert %></p>
						<% end %>
					</div>
			</div>
			<%= yield %>
		</div>
			
		<footer class="row">
			<div class="four columns">
         <h6><strong>Created by iPublic.org</strong></h6>
				 <p>Civic OpenMedia is made by <%= link_to "iPublic.org", "http://www.ipublic.org/" %>, founded by experienced open data folks.</p>
			</div>
       <div class="five columns">
         <h6><strong>OpenMedia site for your community?</strong></h6>
				Interested in starting an OpenMedia site for your community?
			</div>
       <div class="three columns">
         <h6><strong>Need help?</strong></h6>
         Licensed under <%= link_to "GPL", "http://www.gnu.org/licenses/gpl.html" %>
         and
				<%= link_to "MIT", "http://www.opensource.org/licenses/mit-license.php" %>
			</div>
		</footer>
	</body>
</html>

app/views/layouts/sites_data_sources_admin.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= content_for?(:title) ? "Civic OpenMedia Online: " + h(yield(:title)) : "Civic OpenMedia Online" %></title>
	  <%= render :partial => 'layouts/assets' %>
		<%= yield(:head) if content_for?(:head) %>
	</head>
	<body>
		<%= render :partial => 'layouts/om_bar' %>
	  
		<div class="container header">
			<%= render :partial => 'layouts/header_admin' %>
		</div>
			
		<div class="container content">
			<div class="row">
				<div class="two columns">
					<%= render :partial => 'layouts/nav_data_sources' %>
				</div>
				<div class="ten columns">
					<%= yield %>
				</div>
			</div>
		</div>
			
		<footer class="row">
			<%= render :partial => 'layouts/footer_admin' %>
		</footer>
	</body>
</html>

app/views/layouts/sites_public.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <%= render :partial => 'layouts/assets' %>
	  <title><%= current_site.label || 'Civic OpenMedia Public' %></title>
	</head>
	<body>
		<div id="wrapper">
			<div class="container header">
				<%= render :partial => 'layouts/header_sites_public' %>
			</div>
			
			<div class="row">
				<div class="four columns">
					<ul>
					  <li><%= render :partial => 'shared/navigation' %>
					  <li><%= link_to 'OpenMedia Community', root_path %><br/>
					  <li><%= link_to 'Site Admin', admin_home_index_path(authority) %>
					</ul>
				</div>
			</div>

			<div class="container content">
				<div class="row">
					<div class="twelve columns">
						<%= yield %>
					</div>
				</div>
			</div>
		
			<footer class="row">
				<%= render :partial => 'layouts/footer_public' %>
			</footer>
		</div>
	</body>
</html>

app/views/layouts/sites_settings_admin.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= content_for?(:title) ? "Civic OpenMedia Online: " + h(yield(:title)) : "Civic OpenMedia Online" %></title>
	  <%= render :partial => 'layouts/assets' %>
		<%= yield(:head) if content_for?(:head) %>
	</head>
	<body>
		<%= render :partial => 'layouts/om_bar' %>
	  
		<div class="container header">
			<%= render :partial => 'layouts/header_admin' %>
		</div>
			
		<div class="container content">
			<div class="row">
				<div class="two columns">
					<%= render :partial => 'layouts/nav_settings' %>
				</div>
				<div class="ten columns">
					<%= yield %>
				</div>
			</div>
		</div>
			
		<footer class="row">
			<%= render :partial => 'layouts/footer_admin' %>
		</footer>
	</body>
</html>

app/views/layouts/sites_topics_admin.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= content_for?(:title) ? "Civic OpenMedia Online: " + h(yield(:title)) : "Civic OpenMedia Online" %></title>
	  <%= render :partial => 'layouts/assets' %>
		<%= yield(:head) if content_for?(:head) %>
	</head>
	<body>
		<%= render :partial => 'layouts/om_bar' %>
	  
		<div class="container header">
			<%= render :partial => 'layouts/header_admin' %>
		</div>
			
		<div class="container content">
			<div class="row">
				<div class="two columns">
					<%= render :partial => 'layouts/nav_topics' %>
				</div>
				<div class="ten columns">
					<%= yield %>
				</div>
			</div>
		</div>
			
		<footer class="row">
			<%= render :partial => 'layouts/footer_admin' %>
		</footer>
	</body>
</html>